### ISSUE TITLE
通过扫描条形码，获取书籍信息

### ISSUE THREAD

**Issue by fayduan** [XJGamma/BookGamma#17]
- 添加书籍界面，点击扫描获取书籍按钮，跳转到扫描条形码界面
- 扫描条形码界面，可选从图片扫描二维码
- 扫描得到ISBN号数据，通过ISBN号进行书籍检索，得到书籍信息，跳转到添加书籍界面，并自动填写书名、页数、图片信息等

**Comment by whenever77** [comment]
点击扫一扫，（需要照相机权限），打开相机对条形码进行扫描？是拍照还是直接扫描？

**Comment by JingkaiTang** [comment]
扫描吧，类似于二维码扫描，可以研究一下这个[ZXing](https://github.com/zxing/zxing)
