### ISSUE TITLE
添加书评

### ISSUE THREAD

**Issue by whenever77** [XJGamma/BookGamma#36]
- 在书评列表界面
  1. 点击添加书评
  2. 选择书籍名称
  3. 输入标题，内容等
  4. 保存
- 在书籍详情界面
  1. 点击添加书评
  2. 选择书籍名称
  3. 输入标题，内容等
  4. 保存

**Comment by fayduan** [comment]
不需要标题了

**Comment by JingkaiTang** [comment]
何解？
内容即标题？
