### ISSUE TITLE
添加书籍界面布局问题

### ISSUE THREAD

**Issue by JingkaiTang** [XJGamma/BookGamma#51]
如图
![残破的布局](http://7sblub.com1.z0.glb.clouddn.com/Screenshot_2016-07-04-16-22-50-164_cn.edu.xjtu.se.bookgamma.png)

**Comment by whenever77** [comment]
![2805691457188952](https://cloud.githubusercontent.com/assets/19368174/17668249/f7a0b2ac-633a-11e6-96df-e0a0ad6eb076.jpg)

**Comment by fayduan** [comment]
已修复，重构了布局
